# Generated by Django 3.2.13 on 2022-05-08 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('ssn', models.CharField(max_length=9)),
                ('dob', models.DateField()),
                ('start_freeze_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_freeze_date', models.DateField(blank=True, null=True)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='uploads/ID/')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='uploads/Passport/')),
                ('driver_license', models.ImageField(blank=True, null=True, upload_to='uploads/Driver/')),
                ('residency', models.ImageField(blank=True, null=True, upload_to='uploads/Residencies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=455)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=455, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('success', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.BooleanField(default=True)),
                ('lname', models.BooleanField(default=True)),
                ('city', models.BooleanField(default=True)),
                ('state', models.BooleanField(default=True)),
                ('zip', models.BooleanField(default=False)),
                ('address_line1', models.BooleanField(default=True)),
                ('address_line2', models.BooleanField(default=False)),
                ('phone', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=True)),
                ('ssn', models.BooleanField(default=True)),
                ('dob', models.BooleanField(default=False)),
                ('start_freeze_date', models.BooleanField(default=False)),
                ('end_freeze_date', models.BooleanField(default=False)),
                ('id_card', models.BooleanField(default=False)),
                ('passport', models.BooleanField(default=False)),
                ('driver_license', models.BooleanField(default=False)),
                ('residency', models.BooleanField(default=False)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
        ),
    ]
