# Generated by Django 3.2.13 on 2022-05-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='status',
            new_name='finished',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='success',
            new_name='succeed',
        ),
    ]
