# Generated by Django 3.2.13 on 2022-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220508_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
