# Generated by Django 3.2.13 on 2022-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_submission_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='finished',
            field=models.BooleanField(choices=[(True, 'Finished'), (False, 'Pending')], default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='succeed',
            field=models.BooleanField(choices=[(True, 'Succeed'), (False, 'Failed')], default=False),
        ),
    ]
