# Generated by Django 3.2.13 on 2022-05-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220508_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
