# Generated by Django 3.2.13 on 2022-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_submission_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='finished',
            field=models.BooleanField(choices=[(True, 'Finished'), (False, 'Processing')], default=False),
        ),
    ]
