# Generated by Django 3.2.13 on 2022-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_submission_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='start_freeze_date',
            new_name='freeze_date',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='end_freeze_date',
            new_name='freeze_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='end_freeze_date',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='start_freeze_date',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ssn',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(),
        ),
    ]
