# Generated by Django 3.2.13 on 2022-05-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220510_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
