# Generated by Django 3.2.13 on 2022-05-11 16:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_client_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='driver_license',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_driver),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_id),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_passport),
        ),
        migrations.AlterField(
            model_name='client',
            name='residency',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_residencies),
        ),
    ]
