# Generated by Django 3.2.13 on 2022-05-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220511_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
