# Generated by Django 3.2.13 on 2022-05-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='suffix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
