# Generated by Django 3.2.13 on 2022-05-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220512_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='succeed',
            field=models.BooleanField(choices=[(True, 'Successful'), (False, 'Failed')], default=False),
        ),
    ]
