# Generated by Django 3.2.13 on 2022-05-13 09:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_submission_succeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ssn_card',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_ssn_card),
        ),
        migrations.AddField(
            model_name='client',
            name='utility_bill',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_utility_bill),
        ),
    ]
