# Generated by Django 3.2.13 on 2022-05-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220513_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['created_at']},
        ),
    ]
